### PR TITLE
This PR allows to upgrade flutter map to the last version

### PR DESCRIPTION
**Pull request by moovida**
Basically it uses the latlong2 lib to substitute the latlong one. 
Example works with flutter_map 0.13.1

### CODE REVIEW

**Comment by HugoHeneault** [comment]
LGTM. Thanks alot! We're now `flutter_map` 0.13.1 compatible. 👏

**Comment by moovida** [comment]
Thanks for the quick merge :-)

**Comment by HugoHeneault** [comment]
I'm going to release a new version soon. Will keep you updated with that!

**Comment by HugoHeneault** [comment]
Published 1.2.0 :-)

**Pull request merged**
